### ISSUE TITLE
Set up a GitHub Actions workflow

### ISSUE THREAD

**Issue by phenaproxima** [phenaproxima/drupal-suite#1]
This project will be tested using GitHub Actions.

We'll need to set up a workflow that builds the project (basically a `composer install`). The workflow should do that, and:

* Test against a matrix of PHP 8.1, 8.2, and 8.3
* Also against Ubuntu, macOS, and Windows.
* The `web` directory should be served by Apache or nginx (we can't use the PHP built-in server because it's single-threaded).
* Run automatically every 12 hours, and when it's triggered manually.

**Comment by TravisCarden** [comment]
@phenaproxima, I can give you a PR that does all of this _on Linux only_ that you can merge _today_. But macOS and Windows are taking a lot longer to figure out. Would you like an 80% value PR now and the rest in maybe a week? Or do you want to wait to get it all when I'm done?

**Comment by phenaproxima** [comment]
Let's take the 80%! Can you just open a follow-up issue to add support for Windows and macOS too?
