### ISSUE TITLE
Discussion of Captcha vs Antibot

### ISSUE THREAD

**Issue by pameeela** [phenaproxima/drupal-suite#13]
Follow up from https://github.com/phenaproxima/drupal-suite/issues/2

Captcha has been included already, but I raised that I prefer [Antibot](https://www.drupal.org/project/antibot). Moving the conversation here to avoid hijacking the other issue.

**Comment by pameeela** [comment]
Anecdotally we have found Antibot works quite well. Captcha is a bit of a pain with the API key and domain whitelist, as well as occasional weird caching issues that prevent forms from being submitted. Certainly open to others' experiences though, this is just based on mine in the last 2-3 years.

Regarding the config, webform has a setting to enable Antibot for all forms:
![Screenshot 2024-04-23 at 1 08 12 pm](https://github.com/phenaproxima/drupal-suite/assets/961993/58f68b2f-a263-44be-b199-38a9ab437d42)

**Comment by mandclu** [comment]
The agency that I used to work at used to find that the combination of Antibot and Honeypot were actually more effective than Captcha, but I have heard anecdotally that bots are starting to defeat these too.

This thread started with a desire to protect the contact form provided by Webform, and I believe that Webform works with both Antibot and Honeypot out of the box.

Two newer solutions are Spam Master and Spam Bot. I haven't used either, but being honest I wonder if combating spam will always be a cat-and-mouse game that requires evolving solutions.

**Comment by phenaproxima** [comment]
I think we can close this issue out now; if we want to change our anti-spam module choices, we can always do that later in separate issues.
